// Mocks generated by Mockito 5.4.6 from annotations
// in resume_builder/test/services/ats_checking_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:resume_builder/constants/openai_service.dart' as _i5;
import 'package:resume_builder/services/ai_embedding_service.dart' as _i3;
import 'package:resume_builder/services/ai_resume_enhancer.dart' as _i4;
import 'package:resume_builder/services/ai_service_manager.dart' as _i8;
import 'package:resume_builder/services/ai_text_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAITextService_0 extends _i1.SmartFake implements _i2.AITextService {
  _FakeAITextService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAIEmbeddingService_1 extends _i1.SmartFake
    implements _i3.AIEmbeddingService {
  _FakeAIEmbeddingService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAIResumeEnhancer_2 extends _i1.SmartFake
    implements _i4.AIResumeEnhancer {
  _FakeAIResumeEnhancer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OpenAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIService extends _i1.Mock implements _i5.OpenAIService {
  MockOpenAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConfigured => (super.noSuchMethod(
        Invocation.getter(#isConfigured),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<String> generateText({
    required String? systemPrompt,
    required String? userPrompt,
    String? model = 'gpt-4o-mini',
    int? maxTokens = 400,
    double? temperature = 0.7,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateText,
          [],
          {
            #systemPrompt: systemPrompt,
            #userPrompt: userPrompt,
            #model: model,
            #maxTokens: maxTokens,
            #temperature: temperature,
          },
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateText,
            [],
            {
              #systemPrompt: systemPrompt,
              #userPrompt: userPrompt,
              #model: model,
              #maxTokens: maxTokens,
              #temperature: temperature,
            },
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [AIServiceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIServiceManager extends _i1.Mock implements _i8.AIServiceManager {
  MockAIServiceManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  _i2.AITextService get textService => (super.noSuchMethod(
        Invocation.getter(#textService),
        returnValue: _FakeAITextService_0(
          this,
          Invocation.getter(#textService),
        ),
      ) as _i2.AITextService);

  @override
  _i3.AIEmbeddingService get embeddingService => (super.noSuchMethod(
        Invocation.getter(#embeddingService),
        returnValue: _FakeAIEmbeddingService_1(
          this,
          Invocation.getter(#embeddingService),
        ),
      ) as _i3.AIEmbeddingService);

  @override
  _i4.AIResumeEnhancer get resumeEnhancer => (super.noSuchMethod(
        Invocation.getter(#resumeEnhancer),
        returnValue: _FakeAIResumeEnhancer_2(
          this,
          Invocation.getter(#resumeEnhancer),
        ),
      ) as _i4.AIResumeEnhancer);

  @override
  bool get areModelsLoaded => (super.noSuchMethod(
        Invocation.getter(#areModelsLoaded),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [AIEmbeddingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIEmbeddingService extends _i1.Mock
    implements _i3.AIEmbeddingService {
  MockAIEmbeddingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<double>> generateEmbedding(String? text) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateEmbedding,
          [text],
        ),
        returnValue: _i6.Future<List<double>>.value(<double>[]),
      ) as _i6.Future<List<double>>);

  @override
  _i6.Future<double> calculateSimilarity(
    String? text1,
    String? text2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateSimilarity,
          [
            text1,
            text2,
          ],
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<Map<String, double>> matchResumeWithJob({
    required Map<String, String>? resumeSections,
    required String? jobDescription,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matchResumeWithJob,
          [],
          {
            #resumeSections: resumeSections,
            #jobDescription: jobDescription,
          },
        ),
        returnValue: _i6.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i6.Future<Map<String, double>>);

  @override
  _i6.Future<List<String>> getATSOptimizationSuggestions({
    required String? resumeContent,
    required String? jobDescription,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getATSOptimizationSuggestions,
          [],
          {
            #resumeContent: resumeContent,
            #jobDescription: jobDescription,
          },
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> extractKeywords(String? jobDescription) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractKeywords,
          [jobDescription],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<double> calculateKeywordMatch({
    required String? resumeContent,
    required List<String>? keywords,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateKeywordMatch,
          [],
          {
            #resumeContent: resumeContent,
            #keywords: keywords,
          },
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);
}
